### ISSUE TITLE
LoadError while running Pkg.test("Mocha")

### ISSUE THREAD

**Issue by kleinash** [pluskid/Mocha.jl#173] opened 2016-01-18 11:59 UTC
Hi,

While running Pkg.test("Mocha") with GPU backend enabled I get a warning and an error: 

```julia
WARNING: convert(::Type{Ptr}, ::Int64) methods should be converted to be methods of unsafe_convert
 in depwarn at deprecated.jl:73
 [inlined code] from deprecated.jl:418
 in unsafe_convert at no file:0
```

```julia
while loading ~/.julia/v0.4/Mocha/test/layers/shared-parameters.jl, in expression starting on line 50
ERROR: LoadError: LoadError: Not supported
```

I think it has to do with my version of cuda. 

EDIT: it has nothing to do with my version of cuda - have tried 6.0; 7.0 and 7.5. 

Thx

**Comment by pluskid** [comment] 2016-01-18 13:39
What version of Julia and Mocha are you using? Can you try with
```
Pkg.checkout("Mocha")
```
to see if the warning goes away?

**Comment by kleinash** [comment] 2016-01-18 14:38
No it doesn't unfortunately..

**Comment by kleinash** [comment] 2016-01-22 13:04
Any further news? I tried checkout again and it says its dirty so no go..

**Comment by pluskid** [comment] 2016-01-22 14:59
@kleinash I can reproduce the warning and I'm fixing them now. But the error you got is due to something else. I think your CUDA library is not being loaded properly. Did you set `LD_LIBRARY_PATH` properly? Can you do `Libdl.find_library(["libcudnn"], [""])` in the Julia prompt? If it is empty, then cudnn library cannot be properly found.

**Comment by pluskid** [comment] 2016-01-22 15:23
BTW: `Pkg.checkout` saying dirty means you probably modified Mocha locally. To proceed, you can either commit or discard your local changes.

**Comment by kleinash** [comment] 2016-01-26 09:26
Hi. Thanks for the heads up on dirty. I stashed local changes and checked out. 
I find libcudnn no problem.

Running again I get this error:
ERROR: LoadError: Mocha CUDA kernels not up-to-date. Please re-compile (see documents of BACKEND)

Will take a look at the docs and brb.

**Comment by pluskid** [comment] 2016-01-26 14:50
@kleinash I think your CUDA library is not being loaded properly. Did you set LD_LIBRARY_PATH properly? Can you do Libdl.find_library(["libcudnn"], [""]) in the Julia prompt? If it is empty, then cudnn library cannot be properly found.

**Comment by kleinash** [comment] 2016-01-27 06:42
This is what I get in REPL

```julia
julia> Libdl.find_library(["libcudnn"], [""])
"libcudnn"
```
./bashrc 
```bash
...
export CUDA_HOME=/usr/local/cuda
export LD_LIBRARY_PATH=${CUDA_HOME}/lib64
PATH=${CUDA_HOME}/bin:${PATH}
export PATH
```
and... 
```bash
$ ls /usr/local/cuda/lib64 | grep libcudnn
libcudnn.so
libcudnn.so.4
libcudnn.so.4.0.4
libcudnn_static.a
```

Am I doing something wrong?

**Comment by pluskid** [comment] 2016-01-29 13:12
@kleinash Julia Libdl eats a lot of error information. Can you try `Libdl.dlopen("full-path-to-the-so-file")` to see if you could get a valid pointer or an error message?

You can probably also try (in the shell, instead of Julia REPL) `ldd /usr/local/cuda/lib64/libcudnn.so` to see if any of its dependency libraries are actually not properly resolved.

**Comment by kleinash** [comment] 2016-02-01 10:46
Yah - you're right I get:
```julia
Libdl.dlopen("/usr/local/cuda/lib64/libcudnn.so")
Ptr{Void} @0x000000000231bb90
```
but everything is installed correctly so have to look deeper

**Comment by matthew-lake** [comment] 2016-02-04 10:53
I was experiencing the same problem with CUDA 7.5 and CuDNN 4, but it was partially fixed by reverting to CuDNN 3 - the `unsafe_convert` warnings remained, but the `LoadError` did not occur and `Pkg.test("Mocha")` completed successfully.

**Comment by kleinash** [comment] 2016-02-04 12:38
@matthew-lake  do you know if there is a way to direct Mocha to the libraries? The install guide says this:

 cd <installpath>
    export LD_LIBRARY_PATH=`pwd`:$LD_LIBRARY_PATH

    Add <installpath> to your build and link process by adding -I<installpath> to your compile
    line and -L<installpath> -lcudnn to your link line.

- will downgrade though..

**Comment by pluskid** [comment] 2016-02-04 14:36
Great! 

I have not test Mocha against cuDNN v4 yet. Will try to do it recently when I find some time.

**Comment by amellnik** [comment] 2016-02-17 00:10
I'm seeing something similar, but downgrading cuDNN doesn't seem to work for me.  On windows with either cuDNN 3 or 4, CUDA 7.5 and Mocha master I get:

    LoadError: error compiling init: error compiling create: could not load library ""
    The specified module could not be found.

The folder with cuDNN is on the path.  Is there anything else I can check (or what's the trick to seeing a more descriptive error message)?

**Comment by kleinash** [comment] 2016-02-17 08:39
@amellnik I am in now way good at Windows, and I failed miserably at installing CUDA on Windows. But from what I remember about trying to install python, there was a way to set the global library path: https://msdn.microsoft.com/en-us/library/7d83bc18.aspx  https://msdn.microsoft.com/en-us/library/windows/desktop/ms682586%28v=vs.85%29.aspx. Maybe a global search etc can make sure all the libraries, for Julia and CUDA are set - and try running everything through juliabox. All just suggestions..

**Comment by greenflash1357** [comment] 2016-03-15 10:35
@amellnik Your error is cloesly related to #164.

Mocha with cuDNN 4 and CUDA 7.5 work perfectly fine for me on windows. But on linux, I get the same error when running the tests or initializing the bias of a layer... (CPU backend works)

**Comment by pluskid** [comment] 2016-03-15 18:36
I fixed some breaking API changes in cuDNN v4. The test are now running properly for me on OSX with Julia v0.4, CUDA 7.5 and cudnn v4. I also made the error message more clear if libcuda is not found. If you see something like
```
ERROR: LoadError: LoadError: LoadError: Libcuda not found via Libdl.find_library! Please check installation and ENV configuration
```
Then it means `libcuda` cannot be found be Julia due to missing `LD_LIBRARY_PATH`, etc. You can verify this by running some dummy `test.jl` with the following contents
```julia
  const libcuda = Libdl.find_library(["libcuda"], [""])
  println("!!!")
  println(libcuda)
  println(Libdl.find_library(["libcuda"], [""]))
```
using the same way (the same shell, same environment variable) as you used to test Mocha.

**Comment by greenflash1357** [comment] 2016-03-16 10:59
Thank you very much!
Now with cuDNN v4, tests run without errors on windows and linux!

**Comment by pluskid** [comment] 2016-03-16 14:42
great to hear that!

**Comment by phiber1** [comment] 2016-03-18 02:45
I'm having a Mocha problem along the same lines. I'm on Ubuntu 16.04, Julia 0.4.3, CUDA 7.5.18, and cuDNN version 4.0.7. While Pkg.test("CUDNN") passes with flying colors, Pkg.test("Mocha") fails with the following:

17-Mar 22:35:14:DEBUG:root:Init parameter bias for layer conv1
ERROR: LoadError: LoadError: Not supported
 [inlined code] from /home/ENG.pvt/mark/.julia/v0.4/Mocha/src/cuda/cudnn.jl:53
 in add_tensor4d at /home/ENG.pvt/mark/.julia/v0.4/Mocha/src/cuda/cudnn.jl:172
while loading /home/ENG.pvt/mark/.julia/v0.4/Mocha/test/layers/shared-parameters.jl, in expression starting on line 50
while loading /home/ENG.pvt/mark/.julia/v0.4/Mocha/test/runtests.jl, in expression starting on line 85
================================[ ERROR: Mocha ]================================

failed process: Process(`/usr/bin/julia --check-bounds=yes --code-coverage=none --color=yes /home/ENG.pvt/mark/.julia/v0.4/Mocha/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
ERROR: Mocha had test errors
 in test at ./pkg/entry.jl:803
 in anonymous at ./pkg/dir.jl:31
 in cd at ./file.jl:22

-----
Any suggestions you might have would be greatly appreciated, since this is a show-stopper.

Thanks,
Mark

**Comment by pluskid** [comment] 2016-03-18 05:08
Can you try with the latest git version with `Pkg.checkout("Mocha")`? If that solves the issue, I will make a new release.

**Comment by phiber1** [comment] 2016-03-18 18:41
Excellent, now all tests passed and the error is gone.
Other than several deprecation warnings in binary-cross-entropy-loss.jl:
"WARNING: int(x::AbstractFloat) is deprecated, use round(Int,x) instead.",
the original fatal problem seems to have been corrected.

Thanks again!

**Comment by phiber1** [comment] 2016-03-18 18:48
The imagenet-classifier example notebook now also runs correctly (ignoring all the warnings).
So I'd say your most recent fix would appear solid.

**Comment by pluskid** [comment] 2016-03-23 19:54
Making a new release now. I will close this issue but feel free to re-open it if any other related issue occurred.

**Closed by pluskid** 2016-03-23 19:54 UTC
